# Creates a project from templates/project/.
#
#   cmake -DNAME=<snake_case_name> -P cmake/new_project.cmake
#
# Optional: -DPROJECTS_DIR=<folder> (default: <repo>/projects).

cmake_minimum_required(VERSION 3.28)

cmake_path(GET CMAKE_CURRENT_LIST_DIR PARENT_PATH repo_dir)
set(template_dir "${repo_dir}/templates/project")
if(NOT DEFINED PROJECTS_DIR)
    set(PROJECTS_DIR "${repo_dir}/projects")
endif()

if(NOT DEFINED NAME OR NAME STREQUAL "")
    message(FATAL_ERROR "Usage: cmake -DNAME=<snake_case_name> -P cmake/new_project.cmake")
endif()

if(NOT NAME MATCHES "^[a-z][a-z0-9]*(_[a-z0-9]+)*$")
    message(FATAL_ERROR "'${NAME}' is not snake_case (lowercase letters and digits, words separated by single '_').")
endif()

# The name becomes a namespace and the targets <name>, <name>_lib, <name>_tests.
set(cpp_keywords
    alignas alignof and and_eq asm auto bitand bitor bool break case catch char char8_t char16_t char32_t class
    compl concept const consteval constexpr constinit const_cast continue co_await co_return co_yield decltype
    default delete do double dynamic_cast else enum explicit export extern false float for friend goto if inline
    int long mutable namespace new noexcept not not_eq nullptr operator or or_eq private protected public register
    reinterpret_cast requires return short signed sizeof static static_assert static_cast struct switch template
    this thread_local throw true try typedef typeid typename union unsigned using virtual void volatile wchar_t
    while xor xor_eq
)
set(reserved_names
    std common testing
    all clean help test install package format edit_cache rebuild_cache list_install_components
)
if(NAME IN_LIST cpp_keywords OR NAME IN_LIST reserved_names OR NAME MATCHES "^(pg|cpp_lab)_")
    message(FATAL_ERROR "'${NAME}' is reserved (C++ keyword, existing target or prefix).")
endif()
# generator_example is generated by cmake/generator_check.cmake in the check presets.
if(NAME STREQUAL "generator_example" AND NOT GENERATOR_SELF_TEST)
    message(FATAL_ERROR "'${NAME}' is reserved for the generator's self-test.")
endif()

if(EXISTS "${PROJECTS_DIR}/${NAME}")
    message(FATAL_ERROR "${PROJECTS_DIR}/${NAME} already exists.")
endif()

file(GLOB existing_projects LIST_DIRECTORIES true RELATIVE "${PROJECTS_DIR}" "${PROJECTS_DIR}/*")
foreach(existing IN LISTS existing_projects)
    if(existing STREQUAL "${NAME}_lib" OR existing STREQUAL "${NAME}_tests"
       OR NAME STREQUAL "${existing}_lib" OR NAME STREQUAL "${existing}_tests")
        message(FATAL_ERROR "'${NAME}' would clash with the targets of project '${existing}'.")
    endif()
endforeach()

set(project_dir "${PROJECTS_DIR}/${NAME}")
set(files
    "CMakeLists.txt.in"     "CMakeLists.txt"
    "README.md.in"          "README.md"
    "include/project.hpp.in" "include/${NAME}/${NAME}.hpp"
    "src/project.cpp.in"    "src/${NAME}.cpp"
    "src/main.cpp.in"       "src/main.cpp"
    "tests/test_project.cpp.in" "tests/test_${NAME}.cpp"
)
while(files)
    list(POP_FRONT files template output)
    configure_file("${template_dir}/${template}" "${project_dir}/${output}" @ONLY)
    message(STATUS "Created ${project_dir}/${output}")
endwhile()

message(STATUS "Next: configure (or build once) to pick up the new project; targets ${NAME}, ${NAME}_lib, ${NAME}_tests.")
